### ISSUE TITLE
_absorb() issue

### ISSUE THREAD

**Issue by nilswiersma** [SideChannelMarvels/JeanGrey#6]
In `_absorb()`, `candidates[index]` is overwritten by `new_candidates`, even if this `new_candidates` was empty. The result is that collected outputs only get compared in "consecutive pairs", and not all outputs are compared against each other. A better way to process candidates is by replacing https://github.com/SideChannelMarvels/JeanGrey/blob/eeede12cff9b482fbd8fdca6552a3ecf32d2bff6/phoenixAES/phoenixAES/__init__.py#L508 with the following:

```
if new_candidates != []:
    candidates[index]=new_candidates
else:
    candidates[index] += Cands
```

What do you think? Maybe I missed  something?

**Comment by doegox** [comment]
if I remember well it was to not be stuck on "bad candidates" on some quarters.
I know it's not ideal to drop everything because maybe there were still valid candidates there.
But just appending won't work I think, unless there is a more exhaustive test on all possible pairs.
Now that the test itself is much quicker than initially, this could be doable.
Would you mind having a look and proposing a PR ?

**Comment by doegox** [comment]
well it seems to work :)
thanks for your PR!

**Comment by doegox** [comment]
I pushed a 0.0.3 on pypi
